# Build a Comment Toxicity Model with Deep Learning 

In [1]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [5]:
np.expand_dims??



In [2]:
os.path.join('jigsaw-toxic-comment-classification-challenge','train.csv','train.csv')

'jigsaw-toxic-comment-classification-challenge\\train.csv\\train.csv'

In [3]:
df=pd.read_csv( 
os.path.join('jigsaw-toxic-comment-classification-challenge','train.csv','train.csv')
)

In [4]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\r\nWhy the edits made under my use...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\r\nMore\r\nI can't make any real suggestions...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [5]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \r\n\r\nThat...   
159568  ffee36eab5c267c9  Spitzer \r\n\r\nUmm, theres no actual article ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\r\nAnd ... I really don't think you understa...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [6]:
df.iloc[0]['comment_text']

"Explanation\r\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [7]:
df[df.columns[2:]].iloc[5]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 5, dtype: int64

# preprocessing

In [8]:
#tokenaization useing keras 
from tensorflow.keras.layers import TextVectorization

In [9]:
TextVectorization??

In [10]:
X = df['comment_text']
y= df[df.columns[2:]].values

In [11]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [12]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [13]:
df[df.columns[2:]].values#convert into array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
MAX_FEATURES=20000 #num of word in vocab

In [15]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                              output_sequence_length=1800,
                              output_mode='int')

In [16]:
type(X.values)

numpy.ndarray

In [17]:
vectorizer.adapt(X.values)#

In [18]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [19]:
vectorized_text=vectorizer(X.values)#convert into array

In [20]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[ 645,   76,    2, ...,    0,    0,    0],
       [   1,   54, 2489, ...,    0,    0,    0],
       [ 425,  441,   70, ...,    0,    0,    0],
       ...,
       [   1, 7392,  383, ...,    0,    0,    0],
       [   5,   12,  534, ...,    0,    0,    0],
       [   5,    8,  130, ...,    0,    0,    0]], dtype=int64)>

In [21]:
#tensorflow dataset  pipeline
#map,cache,shuffle,batch,prefetch from tensorflow_sclice,list_file
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)  #help to prevent bottlenecks

In [22]:
batch_X,batch_y=dataset.as_numpy_iterator().next()

In [23]:
batch_X

array([[  469,  8661, 17241, ...,     0,     0,     0],
       [ 9307,   909,   426, ...,     0,     0,     0],
       [  171,   191,   123, ...,     0,     0,     0],
       ...,
       [    1,  3336,    31, ...,     0,     0,     0],
       [    8,    74,    15, ...,     0,     0,     0],
       [    1,     7,   201, ...,     0,     0,     0]], dtype=int64)

In [24]:
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1]], dtype=int64)

In [25]:
len(dataset)

9974

In [26]:
train=dataset.take(int(len(dataset)*.7))
val=dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test=dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))                

In [27]:
len(train)

6981

In [28]:
len(test)

997

In [29]:
len(val)

1994

In [30]:
train_genrator=train.as_numpy_iterator()

In [31]:
train_genrator.next()

(array([[6417,   88,    7, ...,    0,    0,    0],
        [5585, 1437,   20, ...,    0,    0,    0],
        [   2,   24,  491, ...,    0,    0,    0],
        ...,
        [ 129,   52,  998, ...,    0,    0,    0],
        [ 190,    5,    1, ...,    0,    0,    0],
        [  70,   15, 1402, ...,    0,    0,    0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

# Create Sequential model

In [38]:
#1.embeding layer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional,Dense
from keras.layers import Embedding

In [39]:
model = Sequential()
#create a embeding layers
model.add(Embedding(MAX_FEATURES+1,32))
#create a LSTM layers
model.add(Bidirectional(LSTM(32,activation='tanh')))#bidirectional-add info to both direction
#feature extractor fully connected layer
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
#final layer
model.add(Dense(6,activation='sigmoid'))

In [40]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')

In [41]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          640032    
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                      

In [42]:
history=model.fit(train,epochs=1,validation_data=val) 

6981/6981 [==============================] - 12371s 2s/step - loss: 0.0641 - val_loss: 0.0459


# make prediction

In [43]:
batch=test.as_numpy_iterator().next() 

In [48]:
input_text=vectorizer('You freaking suck! i am going to hurt u') 

In [49]:
model.predict(np.expand_dims(input_text,0))


1/1 [==============================] - 0s 206ms/step


array([[0.97868294, 0.06470614, 0.87145483, 0.02312984, 0.6565436 ,
        0.09065226]], dtype=float32)

In [52]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [47]:
res=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 228ms/step


In [53]:
batch=test.as_numpy_iterator().next()

In [54]:
batch_X,batch_y=test.as_numpy_iterator().next()

In [55]:
model.predict(batch_X)

1/1 [==============================] - 0s 312ms/step


array([[1.6578465e-03, 2.3321782e-07, 3.4399831e-04, 2.6611665e-06,
        1.6286371e-04, 1.2039258e-05],
       [2.3946645e-02, 4.9276805e-05, 5.5870847e-03, 2.5014096e-04,
        4.1356492e-03, 7.1451440e-04],
       [3.1152811e-02, 8.5760628e-05, 7.4169622e-03, 4.0040779e-04,
        5.7674004e-03, 1.0902778e-03],
       [5.6584410e-02, 2.0068284e-04, 1.1450242e-02, 8.4888283e-04,
        1.1675836e-02, 1.7744943e-03],
       [9.5534906e-02, 3.9833592e-04, 1.8980572e-02, 1.3957255e-03,
        2.0622130e-02, 3.5496489e-03],
       [4.9216747e-03, 3.1161499e-06, 1.2468299e-03, 2.4867855e-05,
        6.8942958e-04, 7.0036600e-05],
       [4.2928322e-03, 1.8695930e-06, 9.5483731e-04, 1.5405076e-05,
        5.2878831e-04, 5.5347242e-05],
       [2.7893081e-03, 9.3278078e-07, 6.8253058e-04, 8.4501789e-06,
        3.1517926e-04, 3.4350225e-05],
       [2.1915918e-02, 1.4975325e-05, 3.5990605e-03, 9.8548800e-05,
        3.4222163e-03, 3.0933917e-04],
       [2.6389290e-02, 2.9849023e-05,

In [56]:
(model.predict(batch_X)>0.5)

1/1 [==============================] - 0s 303ms/step


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [57]:
(model.predict(batch_X)>0.5).astype(int)

1/1 [==============================] - 0s 291ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [58]:
(model.predict(batch_y)>0.5).astype(int)

1/1 [==============================] - 1s 1s/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# Evaluating Model

In [67]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [68]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [69]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

1/1 [==============================] - 0s 361ms/step


In [70]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8243953585624695, Recall:0.6544240117073059, Accuracy:0.46840521693229675


In [71]:
import tensorflow as tf
import gradio as gr

In [72]:
model.save('toxicity.h5')

In [73]:
input_str = vectorizer('hey i freaken hate you!')

In [74]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 0s 181ms/step


In [75]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [76]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\acer\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)


In [77]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://f06b01ea415d9f2a7b.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces


1/1 [==============================] - 0s 159ms/step
